// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svunqpzuyzdvdfmuylqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dW5xcHp1eXpkdmRmbXV5bHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0ODg4MzMsImV4cCI6MjA3NzA2NDgzM30.bZa5_6VTs9YZAVyIIVlwLHZL1e5QTRscCqTY8n2Pqxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});